num1 = int(input("please enter first number: "))
num2 = int(input("please enter second number: "))
num3 = int(input("please enter third number: "))
num4 = int(input("please enter fourth number: "))
num5 = int(input("please enter fifth number: "))

print(num1 + num2)
print(num1 - num2)
print(num1 * num2)
print(num1 / num2)
print(num1 // num2)
print(num1 % num2)

print(num2 + num3)
print(num2 - num3)
print(num2 * num3)
print(num2 / num3)
print(num2 // num3)
print(num2 % num3)

print(num3 + num4)
print(num3 - num4)
print(num3 * num4)
print(num3 / num4)
print(num3 // num4)
print(num3 % num4)

print(num4 + num5)
print(num4 - num5)
print(num4 * num5)
print(num4 / num5)
print(num4 // num5)
print(num4 % num5)